# Generated by Django 4.2 on 2023-04-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_alter_employer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
