# Generated by Django 4.2 on 2023-04-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0003_employer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in progress', 'Progress'), ('is finished', 'Finished')], default='waiting', max_length=25)),
                ('deadline', models.DateTimeField()),
                ('employers', models.ManyToManyField(related_name='employers', to='employer.employer')),
            ],
            options={
                'verbose_name': 'projects',
                'verbose_name_plural': 'projects',
            },
        ),
    ]
