# Generated by Django 4.2 on 2023-04-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0003_employer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('contributors', models.ManyToManyField(related_name='contributors', to='employer.employer')),
            ],
            options={
                'verbose_name': 'Internship',
                'verbose_name_plural': 'Internship',
            },
        ),
    ]
